(define (problem vector1) (:domain vectorTyped2)
(:objects
	p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 - pos
	a b c d e f g h i j - valor
)
(:init
  (next p1 p2)
  (next p2 p3)
  (next p3 p4)
  (next p4 p5)
  (next p5 p6)
  (next p6 p7)
  (next p7 p8)
  (next p8 p9)
  (next p9 p10)
  (val p1 a)
  (val p2 b)
  (val p3 c)
  (val p4 d)
  (val p5 e)
  (val p6 f)
  (val p7 g)
  (val p8 h)
  (val p9 i)
  (val p10 j)
  (target p1 e)
  (target p2 d)
  (target p3 f)
  (target p4 h)
  (target p5 c)
  (target p6 j)
  (target p7 b)
  (target p8 g)
  (target p9 a)
  (target p10 i)

)

(:goal (forall (?p - pos ?v - valor)
					      (imply (target ?p ?v) (val ?p ?v))
			 )
)
)

