(define (problem aircargo10cg1av5ae) (:domain aircargo)
(:objects
    A1 A2
	C1 C2 C3 C4 C5 C6 C7 C8 C9 C10
	JFK SFO BCN CDG AMS
)
(:init
  (Avion A1)
  (Avion A2)
  (Carga C1)
  (Carga C2)
  (Carga C3)
  (Carga C4)
  (Carga C5)
  (Carga C6)
  (Carga C7)
  (Carga C8)
  (Carga C9)
  (Carga C10)
  (Aeropuerto JFK)
  (Aeropuerto SFO)
  (Aeropuerto BCN)
  (Aeropuerto CDG)
  (Aeropuerto AMS)
  (En C1 SFO)
  (En C2 JFK)
  (En C3 JFK)
  (En C4 BCN)
  (En C5 BCN)
  (En C6 AMS)
  (En C7 AMS)
  (En C8 CDG)
  (En C9 CDG)
  (En C10 SFO)
  (En A1 SFO)
  (En A2 BCN)
)
(:goal (and
    (En C1 JFK)
    (En C2 SFO)
    (En C3 CDG)
    (En C4 AMS)
    (En C5 SFO)
    (En C6 CDG)
    (En C7 JFK)
    (En C8 BCN)
    (En C9 JFK)
    (En C10 AMS)
    (En A1 SFO)
	)
))
